version: '3'

services:
  python-app:
    build: .
    container_name: vk_scam_scanner
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s

